{% set name = "scikit-dsp-comm" %}
{% set version = "1.1.0" %}
{% set sha256 = "d832245abbd52c912d228b3ac4559f89d35d1ca2f881d9da620b96972727debf" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >= 3.6
  run:
    - python >= 3.6
    - numpy
    - matplotlib
    - scipy

test:
  requires:
    - nose
  imports:
    - sk_dsp_comm

about:
  home: https://github.com/mwickert/scikit-dsp-comm
  license: BSD-3-Clause
  license_file: LICENSE.md
  summary: DSP and Comm package.

  description: |
    This package is a collection of functions and classes to support signal processing and communications theory teaching and research. The foundation for this package is scipy.signal. The origin of this package comes from the writing the book Signals and Systems for Dummies, published by Wiley in 2013. The original module for this book is named ssd.py. In scikit-dsp-comm this module is renamed to sigsys.py to better reflect the fact that signal processing and communications theory is founded in signals and systems, a traditional subject in electrical engineering curricula.
  doc_url: http://scikit-dsp-comm.readthedocs.io
  dev_url: https://github.com/mwickert/scikit-dsp-comm

extra:
  recipe-maintainers:
    - chiranthsiddappa
    - mwickert
