travis:
  secure:
    BINSTAR_TOKEN: Kw3uCG+9O6XVXSBr34VJH0hkzLnFsdzC6p43g4y6bGK4QPHeRCmRmVvLF8u2ts4miqtNk9y2c17XkYrgeYjKnN+iVlbqhZSKYecW28ZcI5iuoYN/k4EbE5btUwxCuMb5DTZYaWCisNrc9qTr8ATZzBWnPlnut+K3KK34s04Tt1Z3nPR5L9MDeHHP2TwsEzU6giPW1f5TMjpEXMIYuEHVeQgPsT2CfOsu0fokMvdd4m+ajxnoBEkR8Mo80c2bTbGI9fYjSen1GYjmRBDpq8stO4BCCaHue1Fft5NsFlTlpwVTATrnkvOq4rW73GvTcVD2e5MELd45Ubtbz77WiupgMpRoYpW8/1FB5dttn8NHrdIHhAJZGMAvegT1kHMQzMONzIGkgYNZsqClhDX1AIsIn2e8xfJQjnGoPs15z5Y7eMtBWwxEJgVbQs0E8rYOV1eHSd4Pr1/J66G5eiJWVPZEiNBWm4gVQ8ZB0rphPQQFRTUAFUlvmwpnaWi6J/dvmpNE+hjtiCHZBdYpt9Fcp+DqNR/03yx7k/h1Wns1uYjm1p0pm3ReJfZs8wyw84THoPot83KZsqVz/h2aeAqRFiIRxQ3NDd64J5iSetuMKnlwpAv1NhDmWODLB/SpE81x0pAa5WWd0HDCj6PTEabqvXzAFSakWMC8wsKfpoDYHApco2Y=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
