travis:
  secure:
    BINSTAR_TOKEN: Ck6ICpdPPJIhTKBbFUyOwKZL7hbeYZgBTpf9nCTbpLFOXjtJrx/90e7GvB7bsNdeD8Y0KR8Px5Hg4Z6r6y6ihavzwk03ScP8Q5blhFQi0pBIUjJHk8D1ti0izNwFKVmJzjWz8yQv94UqNFPJQFI6etgZKkFxQW+MhlRjz5vdX5f7f6e2HtqdaS6nWYWns94ymd/VMIrp6wyvn3uRkwP1MdmOgYedshZDRqhuBKzci3vHqgTjUbgFxnksmLm06Ud0XkeH1QUobObAabnf64zBrVGohPyTSzomERqY6tj7hADSVoVw8fBXXAYju9mcsUbcGAFSrb2AyQt93oP84ouh6aaTP3c171clD7E9fCbJwY0j+2U31RlPZFFNE9P2hMQx56BaQC7HMLxNv2XXBDF9iZTPt/HUTJ96AnbmZqW3eZNnQB3F0sewgi66qvvOg/kWgo3GK89/EVI2v18CVVwqcJyFfPgEKLyAT4yJrwRYeFwy+7PfqrGrOLaXJ2NAnov+zCVlzYJyb1KI0yiURgLfJ16bfhZgtZ1VFNhf8kJn4rUdOG1EcUFSUNG6VcNDdAxOZXJWQSU9vzPkNa0FcR+e1J8S6+Lhn9EXX/aBNYSqOxhZEE+Ki+QZ2SA4IpG2ZN9DJ4d1W5Kb2MlISAH5kuxAAcnkDNoCRwwYrVhEOLzC6Jo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
